export const jobList = [
  {
    jobtitle: "Java Developer",
    company: "XYZ Corp.",
    city: "Austin",
    state: "TX",
    country: "US",
    formattedLocation: "Austin, TX",
    source: "Dice",
    date: "Mon, 02 Aug 2017 16:21:00 GMT",
    snippet:
      "looking for an object-oriented Java Developer... Java Servlets,HTML, JavaScript, AJAX, Struts, Struts2, JSF)",
    url: "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
    onmousedown: "	indeed_clk(this, '0000');",
    latitude: 30.27127,
    longitude: -97.74103,
    jobkey: "12345",
    sponsored: false,
    expired: false,
    indeedApply: true,
    formattedLocationFull: "Austin, TX",
    formattedRelativeTime: "11 hours ago",
  },
  {
    jobtitle: "Java Developer",
    company: "XYZ Corp.",
    city: "Austin",
    state: "TX",
    country: "US",
    formattedLocation: "Austin, TX",
    source: "Dice",
    date: "Mon, 02 Aug 2017 16:21:00 GMT",
    snippet: "ESSE JOB É DE NATAÇÃO MERMO",
    url: "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
    onmousedown: "	indeed_clk(this, '0000');",
    latitude: 78,
    longitude: -125,
    jobkey: "123456",
    sponsored: false,
    expired: false,
    indeedApply: true,
    formattedLocationFull: "Austin, TX",
    formattedRelativeTime: "10 hours ago",
  },
  {
    jobtitle: "Javascript Developer",
    company: "Google.",
    city: "Austin",
    state: "TX",
    country: "US",
    formattedLocation: "Austin, TX",
    source: "Dice",
    date: "Mon, 02 Aug 2017 16:21:00 GMT",
    snippet: "VEM COM NOIS MEU PARÇA",
    url: "https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
    onmousedown: "	indeed_clk(this, '0000');",
    latitude: 30,
    longitude: -85,
    jobkey: "123457",
    sponsored: false,
    expired: false,
    indeedApply: true,
    formattedLocationFull: "Austin, TX",
    formattedRelativeTime: "48 hours ago",
  },
];
